Dev
avalon-dev-j30/lab-3-ustinovsa pull request #1
Opened 2019-06-03 19:35 UTC by ustinovsa

@konivex  прошу проверить.

2019-06-04 20:50 UTC, konivex requested changes
Исправьте замечание.

2019-06-04 20:50 UTC, konivex commented on src/ru/avalon/java/actions/FileScanAction.java
> +    public void close() throws Exception {
Забыли service закрыт.
Учитывая, что во всех классах код метода один и тот же, то напрашивается мысль перенести этот код в интерфейс Action.

2019-06-04 21:09 UTC, ustinovsa commented on src/ru/avalon/java/actions/FileScanAction.java
> +    public void close() throws Exception {
@konivex согласен, перенес close() как default метод интерфейса Action
спасибо!

2019-06-04 21:28 UTC, ustinovsa commented
see last commit, thnx

2019-06-06 15:24 UTC, konivex approved these changes
Зачтено.

2019-06-07 05:49 UTC, merged